### ISSUE TITLE
How to bring ezid-ops repo to the ezid servers

### ISSUE THREAD

**Issue by jsjiang** [CDLUC3/ezid#418]
The ezid-ops is a private repository contains EZID operational documentation and scripts. Is there a way to bring this repo on to the EZID servers without affecting the EZID application deployment procedure.

**Comment by mariagould** [comment]
Decision per sprint meeting May 9:
- Set up scripts in a separate public repo
- Set up internal documentation in a private repo (ezid-docs-internal)

Once these repos are sorted, Ashley will do setup on server.

**Comment by jsjiang** [comment]
Renamed ezid-ops to ezid-docs-internal

**Comment by jsjiang** [comment]
Created a public repo https://github.com/CDLUC3/ezid-ops-scripts for EZID operational scripts. Moved script "verify_ezid_after_patching.py" and associated test records from the ezid-docs-internal to here.

**Comment by jsjiang** [comment]
Ashley added ezid-ops-scripts repo to the puppet deployment workflow. Puppet now deploys ezid-ops-scripts repo to all uc3-ezid-ui hosts.  The hiera attribute to use is scripts-revision.  This requires tagging the scipts repo:
```
# fqsn/uc3-ezid-ui-prd.yaml
#
uc3_ezid_ui::config:
  production:
    ensure_service: 'running'
    deployment_level: 'settings'
    project_revision: '3.1.3'
    scripts_revision: '0.0.1'
    run_ansible: true
[cut]
```
