### ISSUE TITLE
Revise WAF rules to block more malicious access

### ISSUE THREAD

**Issue by jsjiang** [CDLUC3/ezid#477]
We  may need to revise custom WAF rules to restrict access to the end points that are not covered in the initial version.

For example the following accesses from 92.119.179.86 should all be blocked:

- Time period: Sept 25, 8-11am
- Total access: 50,751
- Allow: 48%
- Block: 52%
- Allowed URIs:

> - /doc/
> - /account/
> - /demo/
> - /static/locale/en
> - /static/info/
> - /
> - /admin/login/
> - /login
> - Index.asp, index.jsp, index.cgi, index.htm, etc.

Action: Revise custom WAF rules to 

- restrict access to doc, account, demo endpoints
- Block access to the index pages

**Comment by jsjiang** [comment]
![Image](https://github.com/CDLUC3/ezid/assets/12803478/1adb4181-597f-494f-a4c8-99a0c9ec6599)

**Comment by jsjiang** [comment]
10/3-10/10: over 11K access on '/status' and the majority came from Duke University. It looks like they have a process that accesses the /status page once every minute. Should we ask why they do this?

**Comment by jsjiang** [comment]
Limit access to the `account/pwreset` page:
* There were over 700 access to this page during 10/12- 10/17
* Some are GETs and some are POSTs
* 65% were allowed, 35% were blocked.
* The majority came from  a few IP addresses

**Comment by jsjiang** [comment]
Investigate if we should limit access to the `/oai` 
* on 10/11 there were over 25K  access from  IP address 178.25.156.200 (Berlin, Germany)

**Comment by jsjiang** [comment]
2024-07-17:
* Modify rate-limit rule to rate limiting more url patterns
* The rate-limit rule blocks accesses when requests for a certain URL patten from the same IP address is over 100 in a 5 minutes window

```
- Action:
    Block: {}
  Name: rate-limit
  Priority: 13
  Statement:
    RateBasedStatement:
      AggregateKeyType: IP
      Limit: 100
      ScopeDownStatement:
        RegexMatchStatement:
          FieldToMatch:
            UriPath: {}
          RegexString: (^\/login|^\/logout|^\/learn|^\/home|^\/account|^\/contact|^\/dashboard|^\/demo|^\/doc|^\/doanload|^\/manage|^\/search|^\/status|^\/version|^\/s3_download|^\/admin|^\/monitor|^\/$)
          TextTransformations:
          - Priority: 0
            Type: NONE
  VisibilityConfig:
    CloudWatchMetricsEnabled: true
    MetricName: rate-limit
    SampledRequestsEnabled: true
```

Added URL patterns:
```
d-bash-4.2$ diff uc3-ezidui-stg-waf.rules_output.20240717.yaml uc3-ezidui-stg-waf.rules.input.20240717_test_v1.yaml
192c192
<           RegexString: (^\/login|^\/learn|^\/contact|^\/$)
---
>           RegexString: (^\/login|^\/logout|^\/learn|^\/home|^\/account|^\/contact|^\/dashboard|^\/demo|^\/doc|^\/doanload|^\/manage|^\/search|^\/status|^\/version|^\/s3_download|^\/admin|^\/monitor|^\/$)
-bash-4.2$ 
```
