### ISSUE TITLE
Create a new WAF rule to limit access to newly added ajax_index_form form

### ISSUE THREAD

**Issue by jsjiang** [CDLUC3/ezid#794]
A new form `home/ajax_index_form` was added to avoid reloading page when switching between creating demo ARK and DOI (#541). Add a WAF rule to restrict spam accesses

**Comment by adambuttrick** [comment]
Per team discussion on 2024/11/26, adding this WAF rule should be treated as a dependency for release of the related UI fixes.

**Comment by jsjiang** [comment]
The `home/ajax_index_form` form should have been covered by current `rate-limit` rule by regexstring matching `^\/home`. Test it in the ezid-stg environment (we do not have waf for ezid-dev) with the `home/ajax_index_form` release.

```
- Action:
    Block: {}
  Name: rate-limit 
  Priority: 13
  Statement:
    RateBasedStatement:
      AggregateKeyType: IP
      Limit: 100
      ScopeDownStatement:
        RegexMatchStatement:
          FieldToMatch:
            UriPath: {}
          RegexString: (^\/login|^\/logout|^\/learn|^\/home|^\/account|^\/contact|^\/dashboard|^\/demo|^\/doc|^\/download|^\/manage|^\/search|^\/status|^\/version|^\/s3_download|^\/admin|^\/monitor|^\/$)
          TextTransformations:
          - Priority: 0
            Type: NONE
  VisibilityConfig:
    CloudWatchMetricsEnabled: true
    MetricName: rate-limit
    SampledRequestsEnabled: true
```
