### ISSUE TITLE
Accessibility fixes: Fix aria-hidden violations in header navigation

### ISSUE THREAD

**Issue by adambuttrick** [CDLUC3/ezid#823]
## Description
The header navigation component (`header.header > nav#js-header__nav`) has an accessibility violation related to improper implementation of `aria-hidden="true"`. When elements are hidden using `aria-hidden="true"`, all focusable content within them should also be inaccessible to ensure a consistent experience for screen reader users.

## Current Behavior
The navigation menu contains focusable elements while being marked as `aria-hidden="true"`, which creates a confusing experience for users of assistive technologies. Currently:

```html
<nav role="navigation" id="js-header__nav" class="header__nav" aria-hidden="true">
  <!-- Contains focusable elements that are still accessible -->
</nav>
```

## Expected Behavior
When the navigation is hidden, all focusable elements within it should also be made inaccessible to maintain consistency with WCAG guidelines.

### Option 2: CSS-based Solution
```css
.header__nav[aria-hidden="true"] {
  display: none;
}

/* If animation is needed, use visibility instead */
.header__nav[aria-hidden="true"] {
  visibility: hidden;
  pointer-events: none;
}
```

## Testing Criteria
- [ ] When navigation is hidden, all focusable elements should be unreachable via keyboard
- [ ] Screen readers should not announce hidden navigation content
- [ ] Navigation toggle functionality should work as expected
- [ ] No visual regression in navigation appearance

## Related Docs
- [WCAG 2.1 Success Criterion 1.3.1: Info and Relationships](https://www.w3.org/WAI/WCAG21/Understanding/info-and-relationships)
- [ARIA: aria-hidden attribute](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-hidden)
